/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JRadioButton;

/**
 *
 * @author Cristian
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        
    }

    public JButton getBotonabrir() {
        return Botonabrir;
    }

    public void setBotonabrir(JButton Botonabrir) {
        this.Botonabrir = Botonabrir;
    }

    public JRadioButton getMayme() {
        return Mayme;
    }

    public void setMayme(JRadioButton Mayme) {
        this.Mayme = Mayme;
    }

    public JRadioButton getMburbuja() {
        return Mburbuja;
    }

    public void setMburbuja(JRadioButton Mburbuja) {
        this.Mburbuja = Mburbuja;
    }

    public JRadioButton getMemay() {
        return Memay;
    }

    public void setMemay(JRadioButton Memay) {
        this.Memay = Memay;
    }

    public JRadioButton getMinsersion() {
        return Mquicksort;
    }

    public void setMinsersion(JRadioButton Minsersion) {
        this.Mquicksort = Minsersion;
    }

    public JRadioButton getMquicksort() {
        return Mseleccion;
    }

    public void setMquicksort(JRadioButton Mquicksort) {
        this.Mseleccion = Mquicksort;
    }

    public JButton getBotonayuda() {
        return Botonayuda;
    }

    public void setBotonayuda(JButton botonayuda) {
        this.Botonayuda = botonayuda;
    }

    public JFileChooser getjFileChooser1() {
        return jFileChooser1;
    }

    public void setjFileChooser1(JFileChooser jFileChooser1) {
        this.jFileChooser1 = jFileChooser1;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jFileChooser1 = new javax.swing.JFileChooser();
        OpcionesMetodos = new javax.swing.ButtonGroup();
        OrganizarN = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Botonabrir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Mburbuja = new javax.swing.JRadioButton();
        Mquicksort = new javax.swing.JRadioButton();
        Mseleccion = new javax.swing.JRadioButton();
        Mayme = new javax.swing.JRadioButton();
        Memay = new javax.swing.JRadioButton();
        Botonayuda = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Minsercion = new javax.swing.JRadioButton();

        jLabel1.setText("1. Seleccione el tipo de ordenamiento ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 520));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setLayout(null);

        Botonabrir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Botonabrir.setText("Abrir y Procesar ");
        jPanel1.add(Botonabrir);
        Botonabrir.setBounds(210, 330, 150, 60);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Seleccione el metodo de ordenamiento ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(170, 30, 280, 40);

        OpcionesMetodos.add(Mburbuja);
        Mburbuja.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Mburbuja.setText("Burbuja");
        Mburbuja.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(Mburbuja);
        Mburbuja.setBounds(80, 100, 67, 23);

        OpcionesMetodos.add(Mquicksort);
        Mquicksort.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Mquicksort.setText("Quicksort");
        Mquicksort.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(Mquicksort);
        Mquicksort.setBounds(330, 100, 77, 23);

        OpcionesMetodos.add(Mseleccion);
        Mseleccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Mseleccion.setText("Por Selección");
        Mseleccion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(Mseleccion);
        Mseleccion.setBounds(190, 100, 100, 23);

        OrganizarN.add(Mayme);
        Mayme.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Mayme.setText("Mayor a Menor ");
        jPanel1.add(Mayme);
        Mayme.setBounds(110, 210, 130, 30);

        OrganizarN.add(Memay);
        Memay.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Memay.setText("Menor a Mayor ");
        jPanel1.add(Memay);
        Memay.setBounds(330, 210, 130, 23);

        Botonayuda.setText("Ayuda");
        jPanel1.add(Botonayuda);
        Botonayuda.setBounds(500, 440, 80, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("¿Como desea ordenar los numeros del Txt?");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 150, 280, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Seleccione el Txt que desea ordenar");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 280, 240, 30);

        OpcionesMetodos.add(Minsercion);
        Minsercion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Minsercion.setText("Insercion");
        jPanel1.add(Minsercion);
        Minsercion.setBounds(450, 100, 90, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Botonabrir;
    public javax.swing.JButton Botonayuda;
    public javax.swing.JRadioButton Mayme;
    public javax.swing.JRadioButton Mburbuja;
    public javax.swing.JRadioButton Memay;
    public javax.swing.JRadioButton Minsercion;
    public javax.swing.JRadioButton Mquicksort;
    public javax.swing.JRadioButton Mseleccion;
    private javax.swing.ButtonGroup OpcionesMetodos;
    private javax.swing.ButtonGroup OrganizarN;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
